// <auto-generated />
using AbrigoPetsBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AbrigoPetsBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171112142339_AddingKeyProperty")]
    partial class AddingKeyProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AbrigoPetsBackend.Data.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<bool>("Castrated");

                    b.Property<DateTime>("DateOfArrival");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTime>("NextVaccine");

                    b.Property<string>("Note");

                    b.Property<string>("Sex");

                    b.Property<string>("Size");

                    b.Property<bool>("ToBeAdopted");

                    b.Property<string>("Type");

                    b.Property<bool>("UpToDateVaccines");

                    b.HasKey("PetId");

                    b.ToTable("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
